### PR TITLE
Move ttyhascolor to after process.jl, fix fake_repl

### PR DESCRIPTION
**Pull request by mkitti**
This PR moves ttyhascolor to after process.jl so that it can compile. It also fixes `fake_repl` to deactivate colors so that the test succeeds.

### CODE REVIEW

**Comment by karan0299** [comment]
Doesn't adding the new file affects the build time?

**Comment by karan0299** [comment]
@mkitti, Can you rebase your branch on mine?
And thanks for your efforts !!

**Comment by mkitti** [comment]
Done. I recommend not to rebase and force push so much. It makes it very difficult to follow and often does not help unless there is a merge conflict.  https://medium.com/@fredrikmorken/why-you-should-stop-using-git-rebase-5552bee4fed1

**Comment by mkitti** [comment]
> Doesn't adding the new file affects the build time?

Someone can worry about that after this is merged. It's necessary to move the code later in the build so that it will compile and I don't see a better place to put it.

**Pull request merged**
